[env]
# for postgresql, 
DATABASE_URL = "postgres://postgres:dev_only_pwd@localhost/db_name"
RUST_LOG = "axum_diesel_async_graphql_template=debug"

# for argon encryption - base64
PWD_KEY = "CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
# for token encryption - base64
TOKEN_SECRET = "9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
PORT = "3000"

# 30 days
TOKEN_DURATION = "2592000"
